# https://jupyterbook.org/customize/config.html

title: "Tsukasa's Portfolio"
author: Tsukasa

# https://jupyterbook.org/en/stable/structure/configure.html#disable-building-files-that-arent-in-the-table-of-contents
only_build_toc_files: true
exclude_patterns:
  - .github/*
  - .pytest_cache/*
  - .venv/*

execute:
  execute_notebooks: "off"

sphinx:
  config:
    # https://myst-parser.readthedocs.io/en/latest/syntax/cross-referencing.html#implicit-targets
    myst_heading_anchors: 4
    # https://jupyterbook.org/en/stable/interactive/interactive.html#plotly
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.7/require.min.js
    suppress_warnings: ["mystnb.unknown_mime_type"]

execute:
  execute_notebooks: "auto"

import plotly.express as px
from IPython.display import HTML

# Wherever you have fig.show() replace it with this code:
HTML(fig.to_html(include_plotlyjs="cdn", full_html=False))